[project]
name = "understand-us-backend"
version = "0.1.0"
description = "UnderstandUs Backend Service"
authors = [
    {name = "DoodleBear"}
]
readme = "README.md"
requires-python = "^3.11"
dependencies = [
    "livekit-agents (>=0.12.17,<0.13.0)",
    "livekit-plugins-assemblyai (>=0.2.3,<0.3.0)",
    "python-dotenv (>=1.0.1,<2.0.0)"

]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-asyncio = "^0.25.3"
pytest-mock = "^3.14.0"
